apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visionx-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "visionx-backend-svc"
spec:
  rules:
    - host: visionx.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: visionx-backend-svc
                port:
                  number: 8000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: visionx-backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visionx-frontend-svc
                port:
                  number: 80
